export const GET_ALL_CHOCOLATES = "GET_ALL_CHOCOLATES"
export const GET_CHOCOLATE_BYID = "GET_CHOCOLATE_BYID"
export const GET_CHOCOLATE_BYNAME = "GET_CHOCOLATE_BYNAME"
export const ADD_CHOCOLATE = "ADD_CHOCOLATE"
export const RESET_STATE = "RESET_STATE"
export const HANDLE_ERROR = "HANDLE_ERROR"
export const CREATE_USER = "CREATE_USER"
export const CREATE_GOOGLE_USER = "CREATE_GOOGLE_USER"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_TYPES = "GET_TYPES"
export const GET_INGREDIENTS = "GET_INGREDIENTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const TOEDIT_PRODUCT = "TOEDIT_PRODUCT"
export const GET_ALL_CAROUSEL = "GET_ALL_CAROUSEL"
export const ADD_INGREDIENT_TYPE_CATEGORIE = "ADD_INGREDIENT_TYPE_CATEGORIE"
export const DELETE_ELEMENT = "DELETE_ELEMENT"
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const GET_INFO = 'GET_INFO'
export const GET_USER_ORDER = 'GET_USER_ORDER';


