### 
POST http://localhost:3001/categories HTTP/1.1
Content-Type: application/json 

{
	"name" : "Sin gluten"
}

###
POST http://localhost:3001/products HTTP/1.1
Content-Type: application/json 

{
	"name" : "Chocolate en Barra Negro",
    "price" : "30",
    "stock" : "2",
    "ingredients" : ["chau"],
    "image": "url.com",
    "score" : "3",
    "types" : "Chocolate",
    "categories" : ["sin gluten", "sin tac"]
}

###
GET http://localhost:3001/products HTTP/1.1